name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./docs

    name: Build Vue
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd ./docs
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1

        with:
          username: 'Hetari'
          reponame: 'Axon'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
