name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2

      # Now run the Vue build action from the docs directory
      - name: Build Vue in docs directory
        run: |
          cd docs
          npx vue-cli-service build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
